languages:
  JavaScript: true
exclude_paths:
- "lib/**"
- "test/**"
- "dist/**"
- "examples/**"
- "bin/**"
- "docs/**"
- "book.json"
- "CNAME"
- "LICENSE"
- "README.md"
- "config.json"
- "package.json"
